Fix bug which prevented enum default values from being integers.
For something like,

    enum SomeEnum { X = 1, Y, Z }

    struct MyStruct {
        1: optional SomeEnum someEnum = 1
    }

We would get the following error upon compliation.

    AttributeError: 'TypeReference' object has no attribute 'validate'

This happened because the system was attempting to link and validate the
constant value `1` before resolving 'SomeEnum' to its TypeSpec.